### ISSUE TITLE
Added SSM to mrecieve

### ISSUE THREAD

**Issue by kiwisherk** [troglobit/mtools#3]
Hi, I needed a way to test SSM, so, I added that ability to mrecieve. I'm not really a Github guru, so I'm not sure how to do an update or offer an update. I can send you the code, if you wish.

Erik
kiwisherk62@gmail.com

**Comment by troglobit** [comment]
Sorry for the late reply, for some reason notifications had been turned off for this repo.

I'd be happy to take your submission, either do a so called pull request (fork repo, push changes to a branch on your repo, then GitHub will suggest in the web interface that you create a pull request back here).  Or you can just attach a `.patch` file of your changes, preferably in unidiff format, to a comment here. For the latter, please let me know if you want attribution in any form for your submission.

**Comment by troglobit** [comment]
`ETIMEDOUT`, adding this myself now instead.
