### ISSUE TITLE
Please make datadir editable

### ISSUE THREAD

**Issue by liuhangbin** [troglobit/mtools#6]
Hi,

Currently, the `datadir` is hardcode to `share/doc/mtools`. But there are many tools called `mtools` , e,g, the gnu [mtools](https://www.gnu.org/software/mtools/). So when I build the package, I have to rename it to other name, like mcast-tools, to avoid conflicts. The `datadir` is hardcoded and unable to change. It would be convenient if you can change it to
```
datadir     ?= $(prefix)/share/doc/mtools
```
BTW, here is the rpm repo I build for testing
https://copr.fedorainfracloud.org/coprs/liuhangbin/mtools/

Thanks

**Comment by troglobit** [comment]
It'll go much quicker if you submit a PR.

**Comment by liuhangbin** [comment]
Sure, I can do it. I just thought it's only a line change and you can do it eaiser. 

I will submit the PR.
